---
title: "Estatística Básica"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
```

<div class="alert alert-danger" role="alert">
**AVISOS!**

- **Prova** sexta-feira dia 30/08 
- entregar **lista2** indicada no link aulas

</div>

# Disciplinas

Esta página abrange o conteúdo das seguintes disciplinas e cursos:

- **CE009 - Introdução à Estatística**
  - E104A - QUÍMICA LIC NOT (N2P)

# Detalhes da oferta da disciplina

- **Período:** primeiro semestre de 2019
- **Professores Responsáveis:**
  - [Elias Teixeira Krainski][], [LEG][]/DEST/UFPR
<!--[Fernando de Pol Mayer]: http://leg.ufpr.br/~fernandomayer
[Wagner Hugo Bonat]: http://leg.ufpr.br/~wbonat 
-->
- **Horários e Locais:**
    - Terça, 19:00 - 21:00, PQ-13
    - Sexta, 21:00 - 23:00, PR-07
- **Horários de atendimento do professor:**
    - Terças 18:00-19:00 (preferencial). Outros horários
      podem ser agendados previamente por email.
- **Frequência**: de acordo com as normas da Universidade, mínimo de 75%
- **Avaliações**:
  - **Três notas** 
    - **Nota 1**: Lista 1 (**23/08**) + Lista 2 (**30/08**) + prova 1 (**30/08**) 
  - **Média final**: a média final será a média das três notas.

- **Segunda chamada**:
  - Só será realizada segunda chamada para alunos que protocolarem o
    pedido, devidamente justificado, junto ao Departamento de
    Estatística.
- **Datas importantes:** De acordo com a [Resolução 64/18 - CEPE][]:
    - **05/08**: Início do semestre letivo
    - **04/12**: Final do semestre letivo
    - **09 a 14/12**: Período de exames

# Programa/objetivos da disciplina

O objetivo desta disciplina é capacitar os alunos em conceitos básicos
de estatística que permitam a interpretação de resultados de análises e
procedimentos estatísticos, bem como a execução de procedimentos e
análises estatística básicas. O curso compreende três grandes tópicos:

- Análise descritiva e exploratória de dados
- Noções de probabilidades e distribuições de probabilidades
- Introdução à procedimentos de inferência estatística

<!-- links -->

[Elias Teixeira Krainski]: http://www.leg.ufpr.br/~elias/
<!--[Fernando de Pol Mayer]: http://leg.ufpr.br/~fernandomayer
[Wagner Hugo Bonat]: http://leg.ufpr.br/~wbonat 
-->>
[LEG]: http://www.leg.ufpr.br
[Resolução 64/18 - CEPE]: http://www.est.ufpr.br/calendario/cepe6418.pdf
