---
title: "Notas"
output:
  html_document:
    toc: false
    code_folding: show
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
mpf <- function(x) {
    x[is.na(x)] <- 0
    l <- mean(sort(x[c(1:3, 5:7, 9:12)])[4:10])
    p <- mean(x[c(4, 8, 13)])
    return(l*4 + p*6)
}
mpfagro <- function(x) {
    x[is.na(x)] <- 0
    l <- mean(sort(x[c(1:3, 5:7, 9:11)])[4:9])
    p <- mean(x[c(4, 8, 12)])
    return(l*4 + p*6)
}
rpf <- function(x)
  ifelse(x<39, 'Reprovado',
  ifelse(x>69, 'Aprovado', 'Final'))
sobe <- function(x){
    ifelse(x >= 66 & x <= 69, 70, x)
}
rf <- function(x)
    ifelse(x<49, 'Reprovado', 'Aprovado')
sobe2 <- function(x){
    ifelse(x >= 48 & x <= 49, 50, x)
}
```

## Escolha a aba de sua turma {.tabset}

### Eng. Amb. (AMB) & Eng. Ind. Mad. (MD)

```{r engamb, echo=FALSE}
nt <- read.csv2('misc/ambMad.csv')
nt$MediaParcial <- ceiling(apply(as.matrix(nt[-1]), 1, mpf))
nt$MediaParcial <- sobe(nt$MediaParcial)
nt$ResultParcial <- rpf(nt$MediaParcial)
## Verifica se alguem que nao deveria fazer fez o exame
## nt$Exame[nt$ResultParcial != "Final" & !is.na(nt$Exame)]
## Aqui foi permitido, mas coloca NA porque nao adiantou
## nt$Exame[nt$ResultParcial != "Final" & !is.na(nt$Exame)] <- NA
## Quem deveria fazer o exame mas nao fez recebe zero
nt$Exame[nt$ResultParcial == "Final" & is.na(nt$Exame)] <- 0
## Calcula media final
nt$MediaFinal <- ceiling((nt$MediaParcial + (nt$Exame * 10))/2)
nt$MediaFinal <- sobe2(nt$MediaFinal)
nt$MediaFinal[nt$ResultParcial != "Final"] <-
    nt$MediaParcial[nt$ResultParcial != "Final"]
nt$ResultFinal <- rf(nt$MediaFinal)
## Arruma ordem das colunas
nt <- nt[, c(1:14, 16:17, 15, 18:19)]
kable(nt, row.names = FALSE)
```

### Biologia

```{r biologia, echo=FALSE}
nt <- read.csv2('misc/bio.csv')
nt$MediaParcial <- ceiling(apply(as.matrix(nt[-1]), 1, mpf))
nt$MediaParcial <- sobe(nt$MediaParcial)
nt$ResultParcial <- rpf(nt$MediaParcial)
kable(nt, row.names = FALSE)
```

### Agronomia

```{r agronomia, echo=FALSE}
nt <- read.csv2('misc/agro.csv')
nt$MediaParcial <- ceiling(apply(as.matrix(nt[-1]), 1, mpfagro))
nt$MediaParcial <- sobe(nt$MediaParcial)
nt$ResultParcial <- rpf(nt$MediaParcial)
kable(nt, row.names = FALSE)
```

### Madeireira Noturno

```{r madeireira, echo=FALSE}
nt <- read.csv2('misc/madNot.csv')
nt$MediaParcial <- ceiling(apply(as.matrix(nt[-1]), 1, mpf))
nt$MediaParcial <- sobe(nt$MediaParcial)
nt$ResultParcial <- rpf(nt$MediaParcial)
## Verifica se alguem que nao deveria fazer fez o exame
## nt$Exame[nt$ResultParcial != "Final" & !is.na(nt$Exame)]
## Aqui foi permitido, mas coloca NA porque nao adiantou
nt$Exame[nt$ResultParcial != "Final" & !is.na(nt$Exame)] <- NA
## Quem deveria fazer o exame mas nao fez recebe zero
nt$Exame[nt$ResultParcial == "Final" & is.na(nt$Exame)] <- 0
## Calcula media final
nt$MediaFinal <- ceiling((nt$MediaParcial + (nt$Exame * 10))/2)
nt$MediaFinal <- sobe2(nt$MediaFinal)
nt$MediaFinal[nt$ResultParcial != "Final"] <-
    nt$MediaParcial[nt$ResultParcial != "Final"]
nt$ResultFinal <- rf(nt$MediaFinal)
## Arruma ordem das colunas
nt <- nt[, c(1:14, 16:17, 15, 18:19)]
kable(nt, row.names = FALSE)
```
